"""initial schema

Revision ID: c75bfe3b8a2e
Revises: 
Create Date: 2026-09-13 03:11:34.242488

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c75bfe3b8a2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_sheet_token',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_in_use_count', sa.Integer(), nullable=False),
    sa.Column('total_usage_count', sa.Integer(), nullable=False),
    sa.Column('max_usage_count', sa.Integer(), nullable=True),
    sa.Column('type_quotas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_active_usage', 'google_sheet_token', ['is_active', 'current_in_use_count'], unique=False)
    op.create_table('navigation_menu_item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_task',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('running_instance_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_metadata',
    sa.Column('stock_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('market_type', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'market_type', name='uq_stock_market')
    )
    op.create_table('system_config',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('task',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('spreadsheet_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('stock_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('market_type', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('running_instance', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_spreadsheet', 'task', ['spreadsheet_id'], unique=False)
    op.create_index('idx_task_status_created', 'task', ['status', 'created_at'], unique=False)
    op.create_index('idx_task_type_status', 'task', ['task_type', 'status'], unique=False)
    op.create_table('task_template',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('backtest_product_result_cache',
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('returns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_task_id', sa.BigInteger(), nullable=True),
    sa.Column('source_step_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_task_id'], ['task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'cache_key', name='uq_batch_cache')
    )
    op.create_table('backtest_sheet_run_lock',
    sa.Column('spreadsheet_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spreadsheet_id', name='uq_lock_spreadsheet')
    )
    op.create_table('google_sheet',
    sa.Column('spreadsheet_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('registry_scope', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_in_use', sa.Boolean(), nullable=False),
    sa.Column('current_task_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_task_id'], ['task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spreadsheet_id', 'registry_scope', name='uq_sheet_scope')
    )
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_log',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_log_task_created', 'task_log', ['task_id', 'created_at'], unique=False)
    op.create_table('task_result',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('stock_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('stock_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('model_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('period_key', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('year_label', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('kline_range', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('best_metric_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('best_metric_value', sa.Double(), nullable=True),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('result_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_created', 'task_result', ['created_at'], unique=False)
    op.create_index('idx_result_period', 'task_result', ['period_key'], unique=False)
    op.create_index('idx_result_stock', 'task_result', ['stock_code'], unique=False)
    op.create_index('idx_result_task_best', 'task_result', ['task_id', 'is_best'], unique=False)
    op.create_index('idx_result_task_step', 'task_result', ['task_id', 'step_index'], unique=False)
    op.create_table('return_series_point',
    sa.Column('task_result_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('index_return', sa.Double(), nullable=True),
    sa.Column('start_return', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['task_result_id'], ['task_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_result_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return_series_point')
    op.drop_index('idx_result_task_step', table_name='task_result')
    op.drop_index('idx_result_task_best', table_name='task_result')
    op.drop_index('idx_result_stock', table_name='task_result')
    op.drop_index('idx_result_period', table_name='task_result')
    op.drop_index('idx_result_created', table_name='task_result')
    op.drop_table('task_result')
    op.drop_index('idx_task_log_task_created', table_name='task_log')
    op.drop_table('task_log')
    op.drop_table('item')
    op.drop_table('google_sheet')
    op.drop_table('backtest_sheet_run_lock')
    op.drop_table('backtest_product_result_cache')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('task_template')
    op.drop_index('idx_task_type_status', table_name='task')
    op.drop_index('idx_task_status_created', table_name='task')
    op.drop_index('idx_task_spreadsheet', table_name='task')
    op.drop_table('task')
    op.drop_table('system_config')
    op.drop_table('stock_metadata')
    op.drop_table('scheduled_task')
    op.drop_table('navigation_menu_item')
    op.drop_index('idx_token_active_usage', table_name='google_sheet_token')
    op.drop_table('google_sheet_token')
    # ### end Alembic commands ###
